from random import randint

lista = ['01 - CORNO MANSO - O que vê a mulher com o outro e só balança a cabeça. ',
'02 - CORNO BANANA - A mulher vai embora e deixa uma penca de filhos.', 
'03 - CORNO XUXA - O que não larga a mulher por causa dos baixinhos.',
'04 - CORNO AZULEJO - Baixinho, quadrado e liso.',
'05 - CORNO GALO - O que tem chifre até nos pés.',
'06 - CORNO PREVENIDO - O que liga para a esposa antes de ir para casa.',
'07 - CORNO ATLETA - Enquanto ele sai para jogar futebol, o Ricardão chega para encher a bola.', 
'08 - CORNO POLÍTICO - O que promete: "Eu vou matar esse cara!"; mas nunca cumpre.',
'09 - CORNO CETICO - Quando vê a mulher com o outro não acredita. ',
'10 - CORNO INFLAÇÃO - A cada dia que passa o chifre aumenta. ',
'11 - CORNO ELÉTRICO - Quando alguém lhe conta que sua mulher esta com outro, responde: "Fica frio que eu tô ligado!" ',
'12 - CORNO SALÁRIO - Baixinho e só comparece uma vez por mês. ',
'13 - CORNO CEBOLA - Quando vê a mulher com outro chora. ',
'14 - CORNO 7 DE SETEMBRO - Aquele que a mulher só da bandeira. ',
'15 - CORNO GELADEIRA - O que leva chifre mas não esquenta. ',
'16 - CORNO IO-IO - Aquele que vai e volta. ',
'17 - CCORNO AMBULÂNCIA - Aquele que quando vê a mulher com outro sai gritando: Uau! Uau! Uau! ',
'18 - CORNO JIBÓIA - O que dorme entre as pernas da mulher. ',
'19 - CORNO BATERIA - O que fica dizendo: "Vou tomar uma solução!". ',
'20 - CORNO PORCO - Aquele que só come resto. ',
'21 - CORNO MORCEGO - Aquele que só aparece a noite para chupar. ',
'22 - CORNO SOCIALISTA - Aquele que não se importa em dividir com os outros. ',
'23 - CORNO ABELHA - O que vai para a rua fazer cera e volta cheio de mé. ',
'24 - CORNO TERREMOTO - Quando vê a mulher com o outro começa a tremer. ',
'25 - CORNO BRAHMA - Aquele que pensa que é o número 1. ',
'26 - CORNO BAVARIA - Aquele que divide a mulher com os amigos. ',
'27 - CORNO GRANJA - O que da casa comida mas é os outros que comem. ',
'28 - CORNO 120 - O que vê a mulher com o outro fazendo 69, sai e vai no boteco tomar um 51. ',
'29 - CORNO PESCADOR - Aquele que prefere segurar a vara. ',
'30 - CORNO DESINFORMADO - Ele é o último a saber. ',
'31 - CORNO RELIGIOSO - Aquele que acha que a mulher da para fazer caridade. ',
'32 - Corno Agressivo - Quando sabe, bate na mulher. ',
'33 - Corno Amnésia - Quando bebe esquece que é corno. ',
'34 - Corno Artista - Acha que levar chifre é uma arte. ',
'35 - Corno Assumido - Assume os chifres e azar para quem se importa. ',
'36 - Corno Ateu - Aquele que leva chifre e não acredita que é corno. ',
'37 - Corno Atrasado - Aquele que é sempre o último a saber que é um. ',
'38 - Corno Atrevido - Aquele que se mete na conversa da mulher com o Ricardão. ',
'39 - Corno Babaca - Aquele que acredita em tudo que a mulher diz. ',
'40 - Corno Bondoso - Aquele que perdoa sempre as fugas da mulher. ',
'41 - Corno Bravo - Aquele que quando chamado de corno quer brigar. ',
'42 - Corno Brincalhão - Aquele que leva chifre o ano inteiro e no carnaval sai fantasiado de Ricardão. ',
'43 - Corno Burro - Aquele que quando é chamado de corno, fica sem entender. ',
'44 - Corno Caçador - Aquele que vive procurando quem lhe bote um par de chifres. ',
'45 - Corno Camarada - Aquele que ainda empresta dinheiro para o Ricardão. ',
'46 - Corno Caninha - Aquele que só chega em casa bêbado. ',
'47 - Corno Canoa - Aquele que é manobrado pela mulher. ',
'48 - Corno Carrapato - Aquele que vive grudado na mulher tentando evitar o chifre. ',
'49- Corno Cheguei - Aquele que quando chega em casa grita bem alto: "Amor, cheguei!" ',
'50 - Corno Churrasco - Aquele que mete a mão no fogo pela mulher.',
'51 - Corno Cigano - Aquele que toda vez que leva chifre, muda de bairro e diz para os vizinhos que veio de São Paulo.',
'52 - Corno Conformado - Aquele que acha que nasceu para ser corno.',
'53 - Corno Crente - Aquele que sempre crê que só entra no céu quem tem chifre.',
'54 - Corno Cuscuz - Aquele que vê e abafa.',
'55 - Corno Denorex - Aquele que não parece, mas é.',
'56 - Corno Desconfiado - Aquele que quando chega em casa procura o Ricardão até debaixo da cama.',
'57 - Corno Descarado - Aquele que leva chifre e ainda sai desfilando com a mulher.',
'58 - Corno Detetive - Aquele que segue a mulher dos cornos e esquece da dele. ',
'59 - Corno de Recado - Aquele que ainda leva bilhete da mulher para o Ricardão. ',
'60 - Corno Educado - Aquele que aprendeu com o pai e nunca deixa de cumprimentar o Ricardão. ',
'61 - Corno Familiar - Aquele que leva chifre de parente. ',
'62 - Corno Famoso - Aquele que por onde passa e reconhecido como tal. ',
'63 - Corno Fofoqueiro - Aquele que leva chifre e sai contando para todo mundo. ',
'64 - Corno Fracassado - Aquele que é doido para ser corno e a mulher não ajuda. ',
'65 - Corno Frio - Aquele que leva chifre e não esquenta. ',
'66 - Corno Galo - Aquele que tem chifre até nos pés, a mulher é uma galinha e ele ainda vive cantando. ',
'67 - Corno Homicida - Aquele que quando sabe que é corno, tenta se matar. ',
'68 - Corno Indeciso - Aquele que quando descobre que não sabe o que faz. ',
'69 - Corno Inocente - Aquele que é corno e não sabe. ',
'70 - Corno Manso - Aquele que evita qualquer confusão com o Ricardão. ',
'71 - Corno Masoquista - Aquele que leva chifre e não larga a mulher. ',
'72 - Corno Medroso - Aquele que fica esperando o Ricardão ir embora. ',
'73 - Corno Mentiroso - Aquele que mente sempre para defender a mulher. ',
'74 - Corno Misterioso - Aquele que esconde a mulher para ninguém ver. ',
'75 - Corno Morcego - Aquele que só aparece à noite para chupar. ',
'76 - Corno Pai de Santo - Aquele que chega em casa e tira o caboclo de cima da mulher. ',
'77 - Corno Papai Noel - Aquele que leva chifres, vai embora e volta por causa das crianças. ',
'78 - Corno Penoso - Aquele que tem pena de deixar a mulher. ',
'79 - Corno Pilatos - Aquele que quando sabe lava as mãos. ',
'80 - Corno Político - Aquele que só faz promessa "Eu vou matar esse cara". ',
'81 - Corno Preguiça - Aquele que só chega atrasado e diz: "Eu ainda te pego". ',
'82 - Corno Radar - Aquele que sabe que é corno a distância. ',
'83 - Corno Repetente - Aquele que troca de mulher mas continua corno. ',
'84 - Corno Revoltado - Aquele que não aceita a realidade. ',
'85 - Corno São Tomé - Aquele que só acredita quando ver. ',
'86 - Corno Secreto - Aquele que está em nosso meio mas ninguém sabe. ',
'87 - Corno Surdo - Aquele que não dá ouvidos a ninguém, sua mulher é uma santa. ',
'88 - Corno Sem Vergonha - Aquele que a mulher bota chifre até com sapatão. ',
'89 - Corno Teimoso - Aquele que leva chifre da mulher e da amante. ',
'90 - Corno Temporal - Aquele que vive dando tempo para deixar a mulher. ',
'91 - Corno Terremoto - Aquele que quando vê a mulher com outro fica tremendo de raiva. ',
'92 - Corno Valente - Aquele que não sabe, mas quando fica sabendo vira uma fera. ',
'93 - Corno Vingador - Aquele que para se vingar dá o rabo na frente da mulher. ',
'94 - Abelha - O que vai para rua fazer cera e volta cheio de mél. ',
'95 - Ateu - Aquele que leva chifre e não acredita. ',
'96 - Brahma - O que pensa que é o número 1',
'97 - Cheguei - Aquele que quando chega em casa grita bem alto: "Querida, cheguei!" ',
'98 - Papai Noel - Aquele que leva chifres, vai embora e volta por causa das crianças. ',
'99 - Terremoto - Quando vê a mulher com outro fica tremendo. ',
'100 - Cebola - Quando vê a mulher com outro só chora.criar loja virtual']

while True:
    nome = str(input('Digite o seu nome: '))
    if nome == '':
        break
    print("Você é o: ", end='')
    print(lista[randint(0,99)])
    